CREATE TABLE IF NOT EXISTS `#__control` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY
,`user_id` INT NOT NULL COMMENT 'J! User ID'
,`stuff` BOOLEAN NOT NULL
,`checked_out` int(11) unsigned NOT NULL DEFAULT '0'
,`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
,`updated` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = MYISAM DEFAULT CHARSET=utf8;
